Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -58,7 +58,8 @@ jobs:
     steps:
       - name: Install Build Dependencies
         run: |
-          sudo apt update && sudo apt upgrade -y
+          sudo apt update 
+          # && sudo apt upgrade -y
           sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget mold tree npm
           # ccache
 
@@ -119,17 +120,22 @@ jobs:
 
       - name: Update and Add SmartDNS Package
         run: |
-          echo "Fetching the latest SmartDNS commit hash"
-          LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/master | cut -f1)
-          [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
-          curl -fsSL https://raw.githubusercontent.com/pymumu/smartdns/master/package/openwrt/Makefile -o feeds/packages/net/smartdns/Makefile
-          sed -i -E "s/^(PKG_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
-          cat feeds/packages/net/smartdns/Makefile
+          echo "Cloning and adding SmartDNS packages"
+          git clone https://github.com/pymumu/smartdns.git package/smartdns
+          git clone https://github.com/pymumu/smartdns-webui.git package/smartdns-webui
+          rm -rf feeds/packages/net/smartdns
+        
+          # echo "Fetching the latest SmartDNS commit hash"
+          # LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/master | cut -f1)
+          # [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
+          # curl -fsSL https://raw.githubusercontent.com/pymumu/smartdns/master/package/openwrt/Makefile -o feeds/packages/net/smartdns/Makefile
+          # sed -i -E "s/^(PKG_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
+          # cat feeds/packages/net/smartdns/Makefile
 
-      - name: Update and Add SmartDNS Web UI Package
-        run: |
-          sed -i "s/MIRROR_HASH:=.*/MIRROR_HASH:=87830094aab9246debb195c944079e4f8b06f9b2fdbc7a3cdf2934277b6135b3/" feeds/packages/net/smartdns/Makefile          
-          cat feeds/packages/net/smartdns/Makefile
+      # - name: Update and Add SmartDNS Web UI Package
+      #   run: |
+      #     sed -i "s/MIRROR_HASH:=.*/MIRROR_HASH:=87830094aab9246debb195c944079e4f8b06f9b2fdbc7a3cdf2934277b6135b3/" feeds/packages/net/smartdns/Makefile          
+      #     cat feeds/packages/net/smartdns/Makefile
       #     echo "Fetching the latest SmartDNS Web UI commit hash"
       #     LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns-webui.git refs/heads/main | cut -f1)
       #     [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
