Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -116,31 +116,13 @@ jobs:
 
       - name: Update and Add SmartDNS Package
         run: |
-          echo "Cloning and adding SmartDNS packages"
-          
-          rm -rf feeds/packages/net/smartdns
-          git clone https://github.com/pymumu/smartdns.git package/smartdns_repo
-          mv package/smartdns_repo/package/openwrt package/smartdns
-          rm -rf package/smartdns_repo
-          sed -i 's#../../lang/rust/rust-package.mk#../../feeds/packages/lang/rust/rust-package.mk#g' package/smartdns/Makefile
-          sed -i "s/MIRROR_HASH:=.*/MIRROR_HASH:=skip/" package/smartdns/Makefile          
-          cat package/smartdns/Makefile
-                  
-          # echo "Fetching the latest SmartDNS commit hash"
-          # LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/master | cut -f1)
-          # [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
-          # curl -fsSL https://raw.githubusercontent.com/pymumu/smartdns/master/package/openwrt/Makefile -o feeds/packages/net/smartdns/Makefile
-          # sed -i -E "s/^(PKG_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
-          # cat feeds/packages/net/smartdns/Makefile
-
-      # - name: Update and Add SmartDNS Web UI Package
-      #   run: |
-      #     sed -i "s/MIRROR_HASH:=.*/MIRROR_HASH:=87830094aab9246debb195c944079e4f8b06f9b2fdbc7a3cdf2934277b6135b3/" feeds/packages/net/smartdns/Makefile          
-      #     cat feeds/packages/net/smartdns/Makefile
-      #     echo "Fetching the latest SmartDNS Web UI commit hash"
-      #     LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns-webui.git refs/heads/main | cut -f1)
-      #     [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
-      #     sed -i -E "s/^(SMARTDNS_WEBUI_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
+          echo "Fetching the latest SmartDNS commit hash"
+          LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/master | cut -f1)
+          [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
+          curl -fsSL https://raw.githubusercontent.com/pymumu/smartdns/master/package/openwrt/Makefile -o feeds/packages/net/smartdns/Makefile
+          sed -i -E "s/^(PKG_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
+          sed -i "s/MIRROR_HASH:=.*/MIRROR_HASH:=skip/" feeds/packages/net/smartdns/Makefile       
+          cat feeds/packages/net/smartdns/Makefile
 
       - name: Update SmartDNS LuCI File
         run: |
