Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -126,13 +126,13 @@ jobs:
           sed -i -E "s/^(PKG_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
           cat feeds/packages/net/smartdns/Makefile
 
-      - name: Update and Add SmartDNS Web UI Package
-        run: |
-          echo "Fetching the latest SmartDNS Web UI commit hash"
-          LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns-webui.git refs/heads/main | cut -f1)
-          [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
-          sed -i -E "s/^(SMARTDNS_WEBUI_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
-          cat feeds/packages/net/smartdns/Makefile
+      # - name: Update and Add SmartDNS Web UI Package
+      #   run: |
+      #     echo "Fetching the latest SmartDNS Web UI commit hash"
+      #     LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns-webui.git refs/heads/main | cut -f1)
+      #     [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
+      #     sed -i -E "s/^(SMARTDNS_WEBUI_SOURCE_VERSION:=).*/\1$LATEST_COMMIT/" feeds/packages/net/smartdns/Makefile
+      #     cat feeds/packages/net/smartdns/Makefile
 
       - name: Update SmartDNS LuCI File
         run: |
