Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -89,19 +89,12 @@ jobs:
 
       - name: Update and Add SmartDNS Package
         run: |
-          echo "Updating SmartDNS Makefile with the latest commit hash"
-      
-          # Get the latest commit hash from the main branch
-          LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/main | cut -f1)
-      
-          # Update the Makefile by replacing the old PKG_SOURCE_VERSION
+          echo "Fetching the latest SmartDNS commit hash"
+          LATEST_COMMIT=$(git ls-remote https://github.com/pymumu/smartdns.git refs/heads/master | cut -f1)
+          [ -z "$LATEST_COMMIT" ] && { echo "Failed to fetch commit hash"; exit 1; }
+          echo "Latest commit: $LATEST_COMMIT"
           sed -i "s/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$LATEST_COMMIT/" custom_repo/feeds/packages/net/smartdns/Makefile
-      
-          # Copy the updated Makefile to the target location
           cp custom_repo/feeds/packages/net/smartdns/Makefile feeds/packages/net/smartdns/Makefile
-      
-          # Display the updated Makefile for verification
-          echo "Updated Makefile:"
           cat feeds/packages/net/smartdns/Makefile
 
       - name: Configure Firmware Image
